
package rdwCall;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RDWSteekproefWebService", targetNamespace = "http://steekproef.rdw/", wsdlLocation = "file:/C:/Users/luppi/Desktop/RDWSteekproefWebService/RDWSteekproefWebService.wsdl")
public class RDWSteekproefWebService_Service
    extends Service
{

    private final static URL RDWSTEEKPROEFWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException RDWSTEEKPROEFWEBSERVICE_EXCEPTION;
    private final static QName RDWSTEEKPROEFWEBSERVICE_QNAME = new QName("http://steekproef.rdw/", "RDWSteekproefWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/luppi/Desktop/RDWSteekproefWebService/RDWSteekproefWebService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RDWSTEEKPROEFWEBSERVICE_WSDL_LOCATION = url;
        RDWSTEEKPROEFWEBSERVICE_EXCEPTION = e;
    }

    public RDWSteekproefWebService_Service() {
        super(__getWsdlLocation(), RDWSTEEKPROEFWEBSERVICE_QNAME);
    }

    public RDWSteekproefWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), RDWSTEEKPROEFWEBSERVICE_QNAME, features);
    }

    public RDWSteekproefWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, RDWSTEEKPROEFWEBSERVICE_QNAME);
    }

    public RDWSteekproefWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RDWSTEEKPROEFWEBSERVICE_QNAME, features);
    }

    public RDWSteekproefWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RDWSteekproefWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RDWSteekproefWebService
     */
    @WebEndpoint(name = "RDWSteekproefWebServicePort")
    public RDWSteekproefWebService getRDWSteekproefWebServicePort() {
        return super.getPort(new QName("http://steekproef.rdw/", "RDWSteekproefWebServicePort"), RDWSteekproefWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RDWSteekproefWebService
     */
    @WebEndpoint(name = "RDWSteekproefWebServicePort")
    public RDWSteekproefWebService getRDWSteekproefWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://steekproef.rdw/", "RDWSteekproefWebServicePort"), RDWSteekproefWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RDWSTEEKPROEFWEBSERVICE_EXCEPTION!= null) {
            throw RDWSTEEKPROEFWEBSERVICE_EXCEPTION;
        }
        return RDWSTEEKPROEFWEBSERVICE_WSDL_LOCATION;
    }

}
