
package rdwCall;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RDWSteekproefWebService", targetNamespace = "http://steekproef.rdw/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RDWSteekproefWebService {


    /**
     * 
     * @param kenteken
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "steekproef", targetNamespace = "http://steekproef.rdw/", className = "rdwCall.Steekproef")
    @ResponseWrapper(localName = "steekproefResponse", targetNamespace = "http://steekproef.rdw/", className = "rdwCall.SteekproefResponse")
    @Action(input = "http://steekproef.rdw/RDWSteekproefWebService/steekproefRequest", output = "http://steekproef.rdw/RDWSteekproefWebService/steekproefResponse")
    public Boolean steekproef(
        @WebParam(name = "kenteken", targetNamespace = "")
        String kenteken);

}
